#!/usr/bin/env bash
# mise description="Install hugo"
# mise depends=[]
# mise sources=[".mise/tasks/dependency/hugo", ".mise.toml"]
# mise outputs=[".bin/hugo"]

cd $root

mkdir -p .bin
curl -LJO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
tar xzf hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz hugo
mv hugo .bin/
touch .bin/hugo
rm -rf hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
